FROM bitnami/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y \
    python3-pip \
    openjdk-17-jdk \
    curl \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PYTHONPATH=/app
ENV CLASSPATH=/app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY src /app/src
WORKDIR /app 