FROM bitnami/spark:3.3.1

USER root

# Instalar dependências Python
RUN apt-get update && apt-get install -y python3-pip python3-dev

# Copiar requirements e instalar
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Preparar diretório para montagem de volume
RUN mkdir -p /app/config
RUN mkdir -p /app/src

# Configurar variável de ambiente
ENV PYTHONPATH=/app

# Permitir acesso ao PySpark para usuário não-root
RUN chmod -R 777 /opt/bitnami/spark/

USER 1001