FROM python:3.9-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Copiar o código fonte
COPY src/ /app/src/
COPY config/ /app/config/

# Configurar variável de ambiente
ENV PYTHONPATH=/app

# Executar o gerador
CMD ["python", "-m", "src.data_generator.generator"]