FROM python:3.9-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Não copiar o código fonte aqui, pois será montado via volume
# Vamos apenas garantir que as pastas existam
RUN mkdir -p /app/src /app/config

# Configurar variável de ambiente
ENV PYTHONPATH=/app
ENV CLASSPATH=/app

# Executar o gerador
CMD ["python", "-m", "src.data_generator.generator"]