# Configurações do gerador de dados

generator:
  # Número de processos paralelos para geração de dados
  num_processes: 4
  
  # Taxa de geração de transações (por segundo)
  rate: 100
  
  # Distribuição de tipos de transação
  transaction_types:
    credit_card: 0.6
    debit_card: 0.2
    transfer: 0.1
    digital_wallet: 0.1
  
  # Configurações de fraude simulada
  fraud:
    # Probabilidade de uma transação ser fraudulenta
    probability: 0.01
    
    # Tipos de fraudes a serem simuladas
    patterns:
      # Múltiplas transações em curto período
      velocity: 0.3
      # Valores muito acima do padrão do usuário
      amount_outlier: 0.3
      # Localização geográfica suspeita
      location_anomaly: 0.3
      # Comportamento de compra anômalo
      behavior_anomaly: 0.1
  
  # Configurações de valores
  amounts:
    credit_card:
      min: 10.0
      max: 5000.0
      mean: 150.0
      std_dev: 300.0
    debit_card:
      min: 5.0
      max: 2000.0
      mean: 80.0
      std_dev: 150.0
    transfer:
      min: 50.0
      max: 10000.0
      mean: 500.0
      std_dev: 1000.0
    digital_wallet:
      min: 5.0
      max: 1000.0
      mean: 70.0
      std_dev: 100.0