# Configurações Kafka

kafka:
  # Conexão
  bootstrap_servers: "kafka:9092"
  
  # Tópicos
  topics:
    raw_transactions: "transactions"
    processed_transactions: "processed-transactions"
    fraud_alerts: "fraud-alerts"
  
  # Configurações do produtor
  producer:
    acks: "all"
    retries: 3
    batch_size: 16384
    linger_ms: 10
    buffer_memory: 33554432
    key_serializer: "StringSerializer"
    value_serializer: "StringSerializer"
  
  # Configurações do consumidor
  consumer:
    group_id: "fraud-detection-group"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    auto_commit_interval_ms: 5000
    key_deserializer: "StringDeserializer"
    value_deserializer: "StringDeserializer"
    max_poll_records: 500
    
  # Configurações de particionamento
  partitioning:
    transactions: 4
    processed: 4
    alerts: 1