# Configurações Spark

spark:
  # Configurações da aplicação
  app:
    name: "Fraud Detection System"
    master: "spark://spark-master:7077"
    
  # Configurações de execução
  executor:
    memory: "2g"
    cores: 2
    instances: 2
    
  # Checkpoint para Streaming
  checkpoint:
    dir: "/tmp/spark-checkpoint"
    
  # Configurações de streaming
  streaming:
    batch_duration: 10  # segundos
    window_duration: 60  # segundos
    slide_duration: 10   # segundos
    
  # Conexão com Kafka
  kafka:
    bootstrap_servers: "kafka:9092"
    starting_offsets: "earliest"
    
  # Formato de saída
  output:
    format: "parquet"
    path: "/data/processed"
    
  # Configurações do modelo
  ml:
    feature_columns:
      - "amount"
      - "hour_of_day"
      - "day_of_week"
      - "transaction_type"
      - "merchant_category"
      - "location_score"
      - "device_score"
    train_test_split: 0.8
    cross_validation_folds: 5